Skip to content
habibhabibkhan954-gif
ceaser
Repository navigation
Code
Pull requests
Agents
Actions
Projects
.github/workflows/main.yml
Update build.yml #4
Triggered via push 1 minute ago
@habibhabibkhan954-gifhabibhabibkhan954-gif
pushed
 4a1d6ee
master
Status
Failure
Total duration
–
Artifacts
–
This workflow graph cannot be shown
A graph will be generated the next time this workflow is run.

Annotations
1 error
Invalid workflow file: .github/workflows/main.yml#L26
You have an error in your yaml syntax on line 26
